#!/usr/bin/env python3
"""Render metrics.json into docs/metrics.md.

metrics.json is the source of truth; the markdown is generated so the two
cannot drift. tests/test_metrics_dictionary.py fails if the committed markdown
is stale or if a detector emits a key the dictionary does not describe.

    python scripts/build_metrics_doc.py          # write docs/metrics.md
    python scripts/build_metrics_doc.py --check  # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DICTIONARY = ROOT / "metrics.json"
DOCUMENT = ROOT / "docs" / "metrics.md"

SCOPES = [
    ("unit_stats", "Per-unit statistics (`unit_stats`)",
     "One entry per sorted unit, computed from its own inter-spike intervals."),
    ("event", "Per-burst fields (`<tier>.events[]`)",
     "One entry per detected event, at all three tiers unless noted."),
    ("spike_participation", "Spike participation (`spike_participation`)",
     "How much of the well's spiking is organised into network bursts."),
    ("tier_metrics", "Per-tier summaries (`<tier>.metrics`)",
     "Aggregated across the events of one tier. Fields not listed here are the "
     "per-event field of the same name, summarised as `{mean, std, cv}`."),
    ("diagnostics", "Diagnostics (`diagnostics`)",
     "What the detector adapted to. Six of these change per well, so they must "
     "be audited against experimental group before any phenotype is reported."),
    ("plot_data", "Plotting payload (`plot_data`, saved as `network_plot_data.npz`)",
     "Per-bin traces and event markers. Not analysis output."),
]


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ") if text is not None else ""


def render(data: dict) -> str:
    keys = data["keys"]
    out: list[str] = []
    out.append("<!-- Generated by scripts/build_metrics_doc.py from metrics.json. Do not edit by hand. -->")
    out.append("")
    out.append("# Metric dictionary")
    out.append("")
    out.append(f"Schema version **{data['schema_version']}**. "
               "`metrics.json` holds the same content in machine-readable form.")
    out.append("")
    out.append(data["description"])
    out.append("")
    out.append("## Published vocabularies")
    out.append("")
    out.append("Abbreviations in the **Published name** column come from these sources.")
    out.append("")
    for source, terms in data.get("vocabularies", {}).items():
        out.append(f"- **{source}** — {terms}")
    out.append("")

    out.append("## Population signals")
    out.append("")
    out.append("Every network metric derives from one of three per-bin traces.")
    out.append("")
    for name, signal in data["signals"].items():
        out.append(f"### `{name}` — {signal['units']}")
        out.append("")
        out.append(f"```\n{signal['expression']}\n```")
        out.append("")
        out.append(signal["note"])
        out.append("")

    for scope, title, blurb in SCOPES:
        entries = {k: v for k, v in keys.items() if v.get("scope") == scope}
        if not entries:
            continue
        out.append(f"## {title}")
        out.append("")
        out.append(blurb)
        out.append("")
        out.append("| Key | Units | Published name | Definition | Formula | Reference | Since | Caveat |")
        out.append("|---|---|---|---|---|---|---|---|")
        for key, entry in entries.items():
            detector = entry.get("detector")
            name = f"`{key}`" + (f" *({detector} only)*" if detector else "")
            definition = _cell(entry.get("definition"))
            if entry.get("definition_biology"):
                definition += " " + _cell(entry["definition_biology"])
            if entry.get("renamed_from"):
                definition += f" Renamed from `{entry['renamed_from']}`."
            published = entry.get("literature_name") or ""
            if entry.get("abbreviation"):
                published = f"**{entry['abbreviation']}** — {published}" if published else f"**{entry['abbreviation']}**"
            formula = entry.get("formula") or entry.get("same_as_event_field") or entry.get("same_as")
            formula = f"`{formula}`" if formula else ""
            out.append("| {} | {} | {} | {} | {} | {} | {} | {} |".format(
                name,
                _cell(entry.get("units")),
                _cell(published),
                definition,
                _cell(formula),
                _cell(entry.get("literature")),
                _cell(entry.get("since_schema")),
                _cell(entry.get("caveat")),
            ))
        out.append("")

    out.append("## Null convention")
    out.append("")
    stats = data["stats_fields"]
    out.append(stats["description"])
    out.append("")
    for field in ("mean", "std", "cv"):
        out.append(f"- `{field}` — {stats[field]}")
    out.append("")
    out.append(stats["null_convention"])
    out.append("")

    out.append("## Keys whose meaning changed")
    out.append("")
    out.append("Read `diagnostics.schema_version` before comparing files. "
               "Its absence means schema 1 or 2.")
    out.append("")
    out.append("| Key | Changed in schema | What changed |")
    out.append("|---|---|---|")
    for key, entry in keys.items():
        if entry.get("changed_in_schema"):
            out.append(f"| `{key}` | {entry['changed_in_schema']} | {_cell(entry.get('caveat'))} |")
    out.append("")
    out.append("## Keys renamed")
    out.append("")
    out.append("| Was | Is now | Schema |")
    out.append("|---|---|---|")
    for key, entry in keys.items():
        if entry.get("renamed_from"):
            out.append(f"| `{entry['renamed_from']}` | `{key}` | {entry.get('since_schema', '')} |")
    out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/metrics.md is out of date")
    args = parser.parse_args()

    rendered = render(json.loads(DICTIONARY.read_text(encoding="utf-8")))

    if args.check:
        current = DOCUMENT.read_text(encoding="utf-8") if DOCUMENT.exists() else ""
        if current != rendered:
            print(f"{DOCUMENT} is out of date; run scripts/build_metrics_doc.py",
                  file=sys.stderr)
            return 1
        return 0

    DOCUMENT.parent.mkdir(parents=True, exist_ok=True)
    DOCUMENT.write_text(rendered, encoding="utf-8")
    print(f"wrote {DOCUMENT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
